server.port=8080
spring.datasource.url=jdbc:h2:mem:platformdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# Let Hibernate create the tables automatically from your Java @Entity classes
spring.jpa.hibernate.ddl-auto=update
# Prevent Spring from executing schema.sql on startup
spring.sql.init.mode=never
